CREATE TABLE department
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    position     VARCHAR(255),
    post         VARCHAR(255),
    joining_date TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_department PRIMARY KEY (id)
);

ALTER TABLE department ADD department_id BIGINT;

ALTER TABLE department ADD CONSTRAINT uc_department_position UNIQUE (position);